In [1]:
import os
import numpy as np
import matplotlib.image as mpimg
from bs4 import BeautifulSoup
%matplotlib inline

## Extract XML file

In [2]:
# Get Intristics
with open('intri.xml', 'r') as f:
    intri = f.read()
intri_data = BeautifulSoup(intri, 'xml')
intri_real = intri_data.find_all('real')
# for i in range(0, len(intri_real)):
    # print(str(intri_real[i]).split('<real>')[1].split("</real>")[0])

In [3]:
# Get Transform
for file in os.listdir("12-10-22:14:13:21"): # define the directory yourself
    filename = os.fsdecode(file)
    if filename.endswith("trans.xml"):
        with open("12-10-22:14:13:21/" + filename, 'r') as f:
            trans = f.read()
        trans_data = BeautifulSoup(trans, 'xml')
        trans_real = trans_data.find_all('real')
        #for i in range(0, len(intri_real)):
            # print(str(trans_real[i]).split('<real>')[1].split("</real>")[0])

## Extract binary file

In [4]:
# depth values
depthValues = np.fromfile("depthBufferSequence.bin", dtype=np.float32)
depthValues = depthValues.reshape(192, 256, -1)
print(depthValues.shape)

# compressed depth values
compressed_data = open('depthBufferSequence', 'rb').read()
decompressed_data = zlib.decompress(compressed_data, wbits=-zlib.MAX_WBITS)
depthValues = np.frombuffer(decompressed_data, dtype=np.float32).reshape(-1, 192, 256)
print(depthValues.shape)

(192, 256, 438)


## Get RGB values

In [5]:
img = mpimg.imread('590518.69072_color.jpeg')
print(img)

[[[121  93  53]
  [121  93  53]
  [121  93  53]
  ...
  [156 128  88]
  [156 128  88]
  [156 128  88]]

 [[121  93  53]
  [121  93  53]
  [121  93  53]
  ...
  [156 128  88]
  [156 128  88]
  [156 128  88]]

 [[121  93  53]
  [121  93  53]
  [121  93  53]
  ...
  [156 128  88]
  [156 128  88]
  [156 128  88]]

 ...

 [[231 216 195]
  [231 216 195]
  [231 216 195]
  ...
  [191 165 114]
  [191 165 114]
  [191 165 114]]

 [[233 218 197]
  [233 218 197]
  [233 218 197]
  ...
  [191 165 114]
  [191 165 114]
  [191 165 114]]

 [[233 218 197]
  [233 218 197]
  [233 218 197]
  ...
  [191 165 114]
  [191 165 114]
  [191 165 114]]]
